[package]
name = "blink_lights"
version = "0.1.0"
authors = ["ronverbs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# gpio-cdev = "0.5.0"
rust_gpiozero = "0.2.0"
